version: '3.1'

services:
  db: 
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=tracker
      - POSTGRES_USER=tracker
      - POSTGRES_PASSWORD=test123

    ports:
      - 5432:5432
